/**
 * Semantic Repository Index - Vector-based code search and understanding
 * Integrates with VectorMemoryStore for intelligent codebase navigation
 */

import { VectorMemoryStore } from './VectorMemoryStore';
import { ASTParser, type FileSymbols, type Symbol } from './ASTParser';
import type { AgentRole, Task } from './types';

export interface CodeChunk {
  id: string;
  file: string;
  startLine: number;
  endLine: number;
  content: string;
  type: 'function' | 'class' | 'interface' | 'type' | 'component' | 'file';
  symbolName?: string;
  description?: string;
  tags: string[];
}

export interface SearchResult {
  chunk: CodeChunk;
  similarity: number;
  reason: string;
}

export interface IndexStats {
  totalFiles: number;
  totalChunks: number;
  totalSymbols: number;
  languages: Record<string, number>;
  largestFile: { path: string; lines: number };
  indexSize: number; // bytes
}

/**
 * SemanticRepoIndex - Intelligent codebase indexing and search
 */
export class SemanticRepoIndex {
  private memoryStore: VectorMemoryStore;
  private astParser: ASTParser;
  private indexed: Set<string>;
  private chunkCache: Map<string, CodeChunk[]>;

  constructor(memoryStore?: VectorMemoryStore, astParser?: ASTParser) {
    this.memoryStore = memoryStore || new VectorMemoryStore();
    this.astParser = astParser || new ASTParser();
    this.indexed = new Set();
    this.chunkCache = new Map();
  }

  /**
   * Index a file and add it to the semantic store
   */
  async indexFile(filePath: string, content: string): Promise<void> {
    // Skip if already indexed
    if (this.indexed.has(filePath)) {
      return;
    }

    // Parse file for symbols
    const fileSymbols = this.astParser.parseFile(filePath, content);

    // Create chunks from the file
    const chunks = this.createChunks(filePath, content, fileSymbols);

    // Store chunks in vector memory
    for (const chunk of chunks) {
      await this.memoryStore.store({
        content: chunk.content,
        metadata: {
          type: 'code',
          timestamp: Date.now(),
          tags: [...chunk.tags, 'code', fileSymbols.language],
          filePath: chunk.file,
          agentRole: 'executor', // Default
          importance: this.calculateImportance(chunk),
        },
        embedding: undefined, // Will be generated by store()
      });
    }

    // Cache chunks
    this.chunkCache.set(filePath, chunks);
    this.indexed.add(filePath);
  }

  /**
   * Create searchable chunks from a file
   */
  private createChunks(filePath: string, content: string, fileSymbols: FileSymbols): CodeChunk[] {
    const chunks: CodeChunk[] = [];
    const lines = content.split('\n');

    // Create chunks for each symbol
    for (const symbol of fileSymbols.symbols) {
      const chunkContent = lines.slice(symbol.startLine, symbol.endLine + 1).join('\n');

      chunks.push({
        id: `${filePath}:${symbol.name}:${symbol.startLine}`,
        file: filePath,
        startLine: symbol.startLine,
        endLine: symbol.endLine,
        content: chunkContent,
        type: this.mapSymbolType(symbol.type),
        symbolName: symbol.name,
        description: symbol.signature,
        tags: this.generateTags(symbol, fileSymbols),
      });

      // Recursively add child symbols (methods in classes)
      if (symbol.children) {
        for (const child of symbol.children) {
          const childContent = lines.slice(child.startLine, child.endLine + 1).join('\n');
          chunks.push({
            id: `${filePath}:${symbol.name}.${child.name}:${child.startLine}`,
            file: filePath,
            startLine: child.startLine,
            endLine: child.endLine,
            content: childContent,
            type: 'function',
            symbolName: `${symbol.name}.${child.name}`,
            description: child.signature,
            tags: [...this.generateTags(symbol, fileSymbols), 'method'],
          });
        }
      }
    }

    // Add full file as a chunk (for files without clear symbols)
    if (chunks.length === 0 || lines.length < 100) {
      chunks.push({
        id: `${filePath}:full`,
        file: filePath,
        startLine: 0,
        endLine: lines.length - 1,
        content,
        type: 'file',
        tags: [fileSymbols.language, 'full-file'],
      });
    }

    return chunks;
  }

  /**
   * Map symbol type to chunk type
   */
  private mapSymbolType(type: Symbol['type']): CodeChunk['type'] {
    if (type === 'function') return 'function';
    if (type === 'class') return 'class';
    if (type === 'interface') return 'interface';
    if (type === 'type') return 'type';
    return 'file';
  }

  /**
   * Generate tags for a symbol
   */
  private generateTags(symbol: Symbol, fileSymbols: FileSymbols): string[] {
    const tags: string[] = [symbol.type];

    // Add language tag
    tags.push(fileSymbols.language);

    // Add export tag if exported
    if (fileSymbols.exports.includes(symbol.name)) {
      tags.push('exported');
    }

    // Add component tag for React components
    if (
      symbol.type === 'function' &&
      symbol.name.match(/^[A-Z]/) &&
      (fileSymbols.language === 'tsx' || fileSymbols.language === 'jsx')
    ) {
      tags.push('component', 'react');
    }

    // Add async tag
    if (symbol.signature?.includes('async')) {
      tags.push('async');
    }

    return tags;
  }

  /**
   * Calculate importance of a chunk (0-1)
   */
  private calculateImportance(chunk: CodeChunk): number {
    let importance = 0.5; // Base importance

    // Exported symbols are more important
    if (chunk.tags.includes('exported')) importance += 0.2;

    // React components are important
    if (chunk.tags.includes('component')) importance += 0.15;

    // Classes are generally important
    if (chunk.type === 'class') importance += 0.1;

    // Longer chunks might be more important
    const lines = chunk.endLine - chunk.startLine;
    if (lines > 50) importance += 0.05;

    return Math.min(importance, 1.0);
  }

  /**
   * Search the codebase semantically
   */
  async search(
    query: string,
    limit: number = 10,
    filters?: {
      files?: string[];
      types?: CodeChunk['type'][];
      tags?: string[];
      minSimilarity?: number;
    },
  ): Promise<SearchResult[]> {
    const memories = await this.memoryStore.search(query, {
      limit,
      threshold: filters?.minSimilarity || 0.6,
      filter: {
        type: 'code',
        tags: filters?.tags,
      },
    });

    const results: SearchResult[] = [];

    for (const memory of memories) {
      const metadata = memory.metadata as any;
      const chunkId = metadata?.chunkId;

      if (!chunkId) continue;

      // Find chunk in cache
      const chunks = this.chunkCache.get(metadata.filePath) || [];
      const chunk = chunks.find(c => c.id === chunkId);

      if (!chunk) continue;

      // Apply filters
      if (filters?.files && !filters.files.includes(chunk.file)) continue;
      if (filters?.types && !filters.types.includes(chunk.type)) continue;

      const similarity = filters?.minSimilarity || 0.6;
      results.push({
        chunk,
        similarity,
        reason: `Semantic match (${(similarity * 100).toFixed(0)}%)`,
      });
    }

    return results;
  }

  /**
   * Find similar code to a given code chunk
   */
  async findSimilar(code: string, limit: number = 5): Promise<SearchResult[]> {
    return this.search(code, limit, { minSimilarity: 0.75 });
  }

  /**
   * Get all chunks for a file
   */
  getFileChunks(filePath: string): CodeChunk[] {
    return this.chunkCache.get(filePath) || [];
  }

  /**
   * Find code by symbol name
   */
  findBySymbol(symbolName: string): CodeChunk[] {
    const results: CodeChunk[] = [];

    for (const chunks of this.chunkCache.values()) {
      for (const chunk of chunks) {
        if (chunk.symbolName === symbolName || chunk.symbolName?.endsWith(`.${symbolName}`)) {
          results.push(chunk);
        }
      }
    }

    return results;
  }

  /**
   * Find code by tags
   */
  findByTags(tags: string[]): CodeChunk[] {
    const results: CodeChunk[] = [];

    for (const chunks of this.chunkCache.values()) {
      for (const chunk of chunks) {
        if (tags.every(tag => chunk.tags.includes(tag))) {
          results.push(chunk);
        }
      }
    }

    return results;
  }

  /**
   * Get index statistics
   */
  getStats(): IndexStats {
    const stats: IndexStats = {
      totalFiles: this.indexed.size,
      totalChunks: 0,
      totalSymbols: 0,
      languages: {},
      largestFile: { path: '', lines: 0 },
      indexSize: 0,
    };

    for (const [file, chunks] of this.chunkCache) {
      stats.totalChunks += chunks.length;

      // Count symbols (non-file chunks)
      stats.totalSymbols += chunks.filter(c => c.type !== 'file').length;

      // Track languages
      const lang = chunks[0]?.tags.find(t => ['typescript', 'javascript', 'tsx', 'jsx'].includes(t));
      if (lang) {
        stats.languages[lang] = (stats.languages[lang] || 0) + 1;
      }

      // Track largest file
      const fileChunk = chunks.find(c => c.type === 'file');
      if (fileChunk) {
        const lines = fileChunk.endLine - fileChunk.startLine;
        if (lines > stats.largestFile.lines) {
          stats.largestFile = { path: file, lines };
        }
      }

      // Estimate size
      for (const chunk of chunks) {
        stats.indexSize += chunk.content.length;
      }
    }

    return stats;
  }

  /**
   * Check if a file is indexed
   */
  isIndexed(filePath: string): boolean {
    return this.indexed.has(filePath);
  }

  /**
   * Remove a file from the index
   */
  removeFile(filePath: string): void {
    this.indexed.delete(filePath);
    this.chunkCache.delete(filePath);

    // Remove from memory store (by filtering)
    // Note: VectorMemoryStore doesn't have a remove method yet
    // This could be added if needed
  }

  /**
   * Clear the entire index
   */
  clear(): void {
    this.indexed.clear();
    this.chunkCache.clear();
    this.astParser.clear();
    // Note: This doesn't clear the memory store
  }

  /**
   * Get the AST parser
   */
  getASTParser(): ASTParser {
    return this.astParser;
  }

  /**
   * Get the memory store
   */
  getMemoryStore(): VectorMemoryStore {
    return this.memoryStore;
  }

  /**
   * Export index as JSON
   */
  exportIndex(): string {
    const data = {
      indexed: Array.from(this.indexed),
      chunks: Array.from(this.chunkCache.entries()),
      symbolGraph: this.astParser.exportGraph(),
      stats: this.getStats(),
    };

    return JSON.stringify(data, null, 2);
  }
}
